### ISSUE TITLE
'disp_filter' is not defined in gray_code_decoder_disp.py

### ISSUE THREAD

**Issue by wjwang0816** [SILI1994/Structured-light-stereo#3]
Hi, SILI1994
Thanks for your great work ! 
There is something to ask for your advice.
When I run "gray_code_decoder_disp.py", I meet a problem is **"NameError: name 'disp_filter' is not defined"**
I also can't find any function or py file named by  'disp_filter'.
Could you give me any advice? thank you!

**Comment by feiran-l** [comment]
Hi there, it is a feature I tried but have not finished. You can just delete that line of code.

**Comment by wjwang0816** [comment]
I see, Thank you for your guidance !!!
